[package]
name = "stackvec"
version = "0.3.0"
edition = "2021"
authors = [ "Lut99" ]
repository = "https://github.com/Lut99/stackvec-rs"
description = "Implements a non-reallocatable, but resizeable, `Vec`-like structure that lives in the stack."


[dependencies]


[features]
default = []
